### ISSUE TITLE
Crash with BucketLib & Ender Bundle mod

### ISSUE THREAD

**Issue by jahirtrap** [ModdingForBlockheads/CookingForBlockheads#575]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.18

### Mod Version

forge-1.18.2-12.0.0

### Describe the Issue

[crash-2022-03-17_14.18.40-client.txt](https://github.com/ModdingForBlockheads/CookingForBlockheads/files/8289951/crash-2022-03-17_14.18.40-client.txt)
[crash-2022-03-17_14.11.59-client.txt](https://github.com/ModdingForBlockheads/CookingForBlockheads/files/8289981/crash-2022-03-17_14.11.59-client.txt)
[BucketLib mod](https://www.curseforge.com/minecraft/mc-mods/bucketlib)
[Ender Bundle mod](https://www.curseforge.com/minecraft/mc-mods/ender-bundle)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Optifine

**Comment by cech12** [comment]
Hey, I am the developer of the BucketLib library mod. 
My mod adds a FluidIngredient and a MilkIngredient to allow recipes related to the content of buckets or fluid containers. It adds an additional cake recipe which is using the MilkIngredient instead of the milk buckets.
The `getItems()` methods of [FluidIngredient](https://github.com/cech12/BucketLib/blob/1.18/src/main/java/cech12/bucketlib/api/crafting/FluidIngredient.java#L77) and [MilkIngredient](https://github.com/cech12/BucketLib/blob/1.18/src/main/java/cech12/bucketlib/api/crafting/MilkIngredient.java#L40) are using the `FluidUtil.getFluidHandler(ItemStack)` method of Forge.
But I cannot say, why `net/minecraftforge/event/AttachCapabilitiesEvent` cannot be found when your mod is calling `getItems()`. :/

**Comment by cech12** [comment]
Maybe the shared code needs to compile against Forge, too?
https://github.com/ModdingForBlockheads/CookingForBlockheads/blob/1.18.x/shared/build.gradle

**Comment by cech12** [comment]
If **balm-3.0.3+0** is installed, the error with the BucketLib mod no longer occurs.
